use devcore_core::AiDetector;

#[test]
fn detects_cursor_in_commit_message() {
    let detector = AiDetector::new();
    assert_eq!(
        detector.detect("cursor: fix auth flow", "user"),
        Some(devcore_core::AiSource::Cursor)
    );
}

#[test]
fn detects_copilot() {
    let detector = AiDetector::new();
    assert_eq!(
        detector.detect("copilot: add tests", "user"),
        Some(devcore_core::AiSource::Copilot)
    );
}

#[test]
fn detects_claude() {
    let detector = AiDetector::new();
    assert_eq!(
        detector.detect("claude: refactor", "user"),
        Some(devcore_core::AiSource::ClaudeCode)
    );
}

#[test]
fn detects_ai_generated_generic() {
    let detector = AiDetector::new();
    assert_eq!(
        detector.detect("AI-generated: feature", "user"),
        Some(devcore_core::AiSource::Unknown)
    );
}

#[test]
fn detects_bot_author() {
    let detector = AiDetector::new();
    assert_eq!(
        detector.detect("update deps", "dependabot[bot]"),
        Some(devcore_core::AiSource::Unknown)
    );
}

#[test]
fn no_detection_for_human_commit() {
    let detector = AiDetector::new();
    assert_eq!(detector.detect("fix: resolve race", "john"), None);
}

#[test]
fn extract_intent_takes_first_line() {
    let detector = AiDetector::new();
    assert_eq!(
        detector.extract_intent("fix auth\n\nDescription"),
        "fix auth"
    );
}

#[test]
fn detect_file_ai_content() {
    let detector = AiDetector::new();
    assert!(detector.detect_file_ai_content("// Generated by AI"));
    assert!(!detector.detect_file_ai_content("fn main() {}"));
}
