use crate::models::AiSource;
use once_cell::sync::Lazy;
use regex::Regex;

// ── Explicit tool-name patterns ──────────────────────────────────────────────
static CURSOR_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?i)\bcursor\b|ai[- ]?generated|ai[- ]?authored|generated by ai").unwrap()
});
static COPILOT_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"(?i)\bcopilot\b|\bgh-copilot\b").unwrap());
static CLAUDE_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"(?i)\bclaude\b|\banthropic\b|\bclaude[- ]?code\b").unwrap());
static WINDSURF_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"(?i)\bwindsurf\b|\bcodeium\b|\bcody\b").unwrap());
static AIDER_RE: Lazy<Regex> = Lazy::new(|| Regex::new(r"(?i)\baider\b").unwrap());
static CHATGPT_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"(?i)\bchatgpt\b|\bgpt[- ]?[3456]\b|\bopenai\b").unwrap());
static TABNINE_RE: Lazy<Regex> = Lazy::new(|| Regex::new(r"(?i)\btabnine\b").unwrap());
static AMAZON_Q_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"(?i)\bamazon q\b|\bcodeWhisperer\b|\bcodewhisperer\b").unwrap());
static CONTINUE_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"(?i)\bcontinue[- ]?dev\b|\bcontinue\.sh\b").unwrap());
static SMALL_AI_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(r"(?i)\bsmolar\b|\bsmol[- ]?ai\b").unwrap());

// ── AI commit-message patterns (conventional-commit style used by agents) ────
// Many AI tools generate messages like "feat: ...", "fix: ...", "refactor: ..." as
// the first line, then a blank line, then a body.  The body often contains phrases
// like "This commit", "The changes", "Updated the".  We flag the combination.
static CONVENTIONAL_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?i)^(feat|fix|refactor|chore|docs|style|test|perf|ci|build|revert)[:(]").unwrap()
});
static AI_BODY_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?i)(this commit|the following|these changes|this (update|change|patch|fix))")
        .unwrap()
});

// ── Bot / automation author patterns ────────────────────────────────────────
static BOT_AUTHORS: Lazy<Vec<Regex>> = Lazy::new(|| {
    vec![
        Regex::new(r"(?i)\[bot\]").unwrap(),
        Regex::new(r"(?i)dependabot").unwrap(),
        Regex::new(r"(?i)renovate").unwrap(),
        Regex::new(r"(?i)github-actions").unwrap(),
        Regex::new(r"(?i)gitlab-ci").unwrap(),
        Regex::new(r"(?i)copilot").unwrap(),
        Regex::new(r"(?i)cursor").unwrap(),
        Regex::new(r"(?i)aider").unwrap(),
        Regex::new(r"(?i)claude").unwrap(),
    ]
});

// ── File-content markers left by AI tools ───────────────────────────────────
static FILE_MARKERS: Lazy<Vec<Regex>> = Lazy::new(|| {
    vec![
        Regex::new(r"(?i)// generated by ai").unwrap(),
        Regex::new(r"(?i)/\* ai-generated").unwrap(),
        Regex::new(r"(?i)// @ai-generated").unwrap(),
        Regex::new(r"(?i)// @copilot").unwrap(),
        Regex::new(r"(?i)// @cursor").unwrap(),
        Regex::new(r"(?i)// @claude").unwrap(),
        Regex::new(r"(?i)// @aider").unwrap(),
        Regex::new(r"(?i)// @windsurf").unwrap(),
        Regex::new(r"(?i)auto-generated by").unwrap(),
        Regex::new(r"(?i)do not edit this file").unwrap(),
    ]
});

/// Detection result with confidence scoring.
#[derive(Debug, Clone)]
pub struct DetectionResult {
    pub source: AiSource,
    /// Confidence 0.0 – 1.0 (0 = pure guess, 1 = certain)
    pub confidence: f64,
    /// Which signals triggered detection
    pub signals: Vec<String>,
}

/// Multi-signal AI detection engine.
pub struct AiDetector;

impl Default for AiDetector {
    fn default() -> Self {
        Self::new()
    }
}

impl AiDetector {
    pub fn new() -> Self {
        Self
    }

    /// Primary detection: combines commit message, author, and diff signals.
    pub fn detect(&self, commit_message: &str, author: &str) -> Option<DetectionResult> {
        let mut signals = Vec::new();
        let mut score: f64 = 0.0;
        let mut source = AiSource::Unknown;

        // Signal 1: explicit tool name in commit message (strongest)
        if let Some((s, name)) = self.match_tool_name(commit_message) {
            source = s;
            score += 0.8;
            signals.push(format!("tool_name:{}", name));
        }

        // Signal 2: AI body pattern in commit message
        if AI_BODY_RE.is_match(commit_message) {
            score += 0.3;
            signals.push("ai_body_pattern".into());
        }

        // Signal 3: bot/automation author
        if let Some(author_match) = self.match_bot_author(author) {
            score += 0.6;
            signals.push(format!("bot_author:{}", author_match));
            if source == AiSource::Unknown {
                source = AiSource::Unknown;
            }
        }

        // Signal 4: conventional commit format (weak alone, strong with other signals)
        if CONVENTIONAL_RE.is_match(commit_message) {
            score += 0.1;
            signals.push("conventional_commit".into());
        }

        // Signal 5: very large diff with many files (AI signature)
        // This is checked externally via detect_with_diff()
        // but we add a lightweight heuristic here based on message length
        if commit_message.len() > 500 {
            score += 0.15;
            signals.push("long_message".into());
        }

        if score < 0.3 {
            return None;
        }

        Some(DetectionResult {
            source,
            confidence: score.min(1.0),
            signals,
        })
    }

    /// Extended detection: adds diff-level signals for higher accuracy.
    pub fn detect_with_diff(
        &self,
        commit_message: &str,
        author: &str,
        files_changed: usize,
        insertions: u32,
        deletions: u32,
    ) -> Option<DetectionResult> {
        let mut result = self.detect(commit_message, author)?;

        // Signal 6: many files changed in one commit (AI batches work)
        if files_changed > 10 {
            result.confidence += 0.15;
            result.signals.push(format!("many_files:{}", files_changed));
        }

        // Signal 7: large insertions with few deletions (AI writes new code, rarely deletes)
        if insertions > 200 && deletions < insertions / 5 {
            result.confidence += 0.1;
            result.signals.push("insert_heavy".into());
        }

        // Signal 8: very balanced insertions/deletions (AI refactors)
        if insertions > 50 && deletions > 50 {
            let ratio = insertions as f64 / deletions as f64;
            if (0.8..=1.2).contains(&ratio) {
                result.confidence += 0.05;
                result.signals.push("balanced_diff".into());
            }
        }

        result.confidence = result.confidence.min(1.0);
        Some(result)
    }

    /// Check if a file's content contains AI markers.
    pub fn detect_file_content(&self, content: &str) -> Option<AiSource> {
        for marker in FILE_MARKERS.iter() {
            if let Some(m) = marker.find(content) {
                let text = m.as_str().to_lowercase();
                if text.contains("copilot") {
                    return Some(AiSource::Copilot);
                }
                if text.contains("cursor") {
                    return Some(AiSource::Cursor);
                }
                if text.contains("claude") {
                    return Some(AiSource::ClaudeCode);
                }
                if text.contains("aider") {
                    return Some(AiSource::Aider);
                }
                if text.contains("windsurf") {
                    return Some(AiSource::Windsurf);
                }
                return Some(AiSource::Unknown);
            }
        }
        None
    }

    /// Extract the first line of a commit message as intent.
    pub fn extract_intent(&self, commit_message: &str) -> String {
        commit_message
            .lines()
            .next()
            .unwrap_or("")
            .trim()
            .to_string()
    }

    fn match_tool_name(&self, msg: &str) -> Option<(AiSource, &'static str)> {
        if CURSOR_RE.is_match(msg) {
            return Some((AiSource::Cursor, "cursor"));
        }
        if COPILOT_RE.is_match(msg) {
            return Some((AiSource::Copilot, "copilot"));
        }
        if CLAUDE_RE.is_match(msg) {
            return Some((AiSource::ClaudeCode, "claude"));
        }
        if WINDSURF_RE.is_match(msg) {
            return Some((AiSource::Windsurf, "windsurf"));
        }
        if AIDER_RE.is_match(msg) {
            return Some((AiSource::Aider, "aider"));
        }
        if CHATGPT_RE.is_match(msg) {
            return Some((AiSource::Unknown, "chatgpt"));
        }
        if TABNINE_RE.is_match(msg) {
            return Some((AiSource::Unknown, "tabnine"));
        }
        if AMAZON_Q_RE.is_match(msg) {
            return Some((AiSource::Unknown, "amazon-q"));
        }
        if CONTINUE_RE.is_match(msg) {
            return Some((AiSource::Unknown, "continue"));
        }
        if SMALL_AI_RE.is_match(msg) {
            return Some((AiSource::Unknown, "smol-ai"));
        }
        None
    }

    fn match_bot_author(&self, author: &str) -> Option<String> {
        for re in BOT_AUTHORS.iter() {
            if let Some(m) = re.find(author) {
                return Some(m.as_str().to_lowercase());
            }
        }
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_cursor_explicit() {
        let d = AiDetector::new();
        let r = d.detect("cursor: fix auth flow", "user").unwrap();
        assert_eq!(r.source, AiSource::Cursor);
        assert!(r.confidence >= 0.7);
    }

    #[test]
    fn detects_copilot_explicit() {
        let d = AiDetector::new();
        let r = d.detect("copilot: add tests", "user").unwrap();
        assert_eq!(r.source, AiSource::Copilot);
    }

    #[test]
    fn detects_claude_explicit() {
        let d = AiDetector::new();
        let r = d.detect("claude: refactor module", "user").unwrap();
        assert_eq!(r.source, AiSource::ClaudeCode);
    }

    #[test]
    fn detects_chatgpt_in_message() {
        let d = AiDetector::new();
        let r = d.detect("gpt-4 generated this function", "user").unwrap();
        assert_eq!(r.source, AiSource::Unknown);
        assert!(r.signals.iter().any(|s| s.contains("chatgpt")));
    }

    #[test]
    fn detects_bot_author() {
        let d = AiDetector::new();
        let r = d.detect("update deps", "dependabot[bot]").unwrap();
        assert!(r.confidence >= 0.5);
        assert!(r.signals.iter().any(|s| s.contains("bot_author")));
    }

    #[test]
    fn no_detection_for_human_commit() {
        let d = AiDetector::new();
        assert!(d.detect("fix: resolve race condition", "john").is_none());
    }

    #[test]
    fn detection_with_many_files_is_higher_confidence() {
        let d = AiDetector::new();
        let r1 = d.detect("cursor: refactor", "user").unwrap();
        let r2 = d
            .detect_with_diff("cursor: refactor", "user", 15, 300, 50)
            .unwrap();
        assert!(r2.confidence > r1.confidence);
    }

    #[test]
    fn detect_file_ai_marker() {
        let d = AiDetector::new();
        assert!(d.detect_file_content("// @copilot suggest").is_some());
        assert!(d
            .detect_file_content("/* ai-generated — do not edit */")
            .is_some());
        assert!(d.detect_file_content("fn main() {}").is_none());
    }

    #[test]
    fn extract_intent_takes_first_line() {
        let d = AiDetector::new();
        assert_eq!(
            d.extract_intent("fix auth\n\nDetailed description"),
            "fix auth"
        );
    }
}
