use crate::models::AiSource;
use regex::Regex;

/// Detects AI-generated commits and file content by scanning for known patterns and author names.
pub struct AiDetector {
    patterns: Vec<AiPattern>,
}

struct AiPattern {
    regex: Regex,
    source: AiSource,
}

impl AiDetector {
    /// Creates a new detector with built-in regex patterns for known AI tools.
    pub fn new() -> Self {
        let patterns = vec![
            AiPattern {
                regex: Regex::new(r"(?i)cursor").unwrap(),
                source: AiSource::Cursor,
            },
            AiPattern {
                regex: Regex::new(r"(?i)copilot").unwrap(),
                source: AiSource::Copilot,
            },
            AiPattern {
                regex: Regex::new(r"(?i)claude|anthropic").unwrap(),
                source: AiSource::ClaudeCode,
            },
            AiPattern {
                regex: Regex::new(r"(?i)windsurf|codeium").unwrap(),
                source: AiSource::Windsurf,
            },
            AiPattern {
                regex: Regex::new(r"(?i)aider").unwrap(),
                source: AiSource::Aider,
            },
            AiPattern {
                regex: Regex::new(r"(?i)ai[- ]?generated|ai[- ]?authored|generated by ai").unwrap(),
                source: AiSource::Unknown,
            },
        ];

        Self { patterns }
    }

    /// Attempts to identify the AI source from a commit message and author name.
    /// Checks the commit message against known patterns first, then falls back to bot-author detection.
    /// Returns `None` if no AI involvement is detected.
    pub fn detect(&self, commit_message: &str, author: &str) -> Option<AiSource> {
        for pattern in &self.patterns {
            if pattern.regex.is_match(commit_message) {
                return Some(pattern.source.clone());
            }
        }

        if self.is_bot_author(author) {
            Some(AiSource::Unknown)
        } else {
            None
        }
    }

    /// Returns `true` if the commit appears to be AI-generated based on message content or author.
    pub fn is_ai_commit(&self, commit_message: &str, author: &str) -> bool {
        self.detect(commit_message, author).is_some()
    }

    fn is_bot_author(&self, author: &str) -> bool {
        let lower = author.to_lowercase();
        lower.contains("bot")
            || lower.contains("[bot]")
            || lower.contains("dependabot")
            || lower.contains("renovate")
            || lower.contains("github-actions")
    }

    /// Extracts the intent (first line) from a commit message.
    pub fn extract_intent(&self, commit_message: &str) -> String {
        let lines: Vec<&str> = commit_message.lines().collect();
        if let Some(first) = lines.first() {
            first.trim().to_string()
        } else {
            commit_message.trim().to_string()
        }
    }

    /// Scans file content for common AI-generation markers and returns `true` if found.
    pub fn detect_file_ai_content(&self, content: &str) -> bool {
        let indicators = [
            "TODO: This code was generated by",
            "// Generated by AI",
            "/* AI-generated",
            "# This file was auto-generated",
            "/// @ai-generated",
        ];

        indicators.iter().any(|ind| content.contains(ind))
    }
}
